name: Deploy PR previews

on:
  # Only run on Staging
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

concurrency: preview-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  build-preview:
    if: github.repository == 'project-chip/matter-handbook'
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.115.4
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive
          fetch-depth: 0
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

