name: Deploy PR previews

on:
  # Only run on Staging
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

concurrency: preview-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  build-preview:
    if: github.repository == 'project-chip/matter-handbook'
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.115.4
    steps:
      - name: This is a workflow that does nothing
        run: echo 'WHERE ARE YOU COMING FROM???????? WHY???? WHY????'



